# Generated by Django 2.2.1 on 2019-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('authorization', '0003_auto_20190722_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.ManyToManyField(to='api.App'),
        ),
    ]
